Evolutime/Models/ErrorViewModel.cs
namespace Evolutime.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Evolutime/Controllers/AgradecimentoController.cs
using Evolutime.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Evolutime.Controllers
{
    public class AgradecimentoController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public AgradecimentoController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Agradecimento()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Evolutime/Controllers/HomeController.cs
using Evolutime.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Evolutime.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Evolutime/Views/Agradecimento/Agradecimento.cshtml
@{
    ViewData["Title"] = "Agradecemos sua visita";
}
<h1>@ViewData["Title"]</h1>

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agradecimento por Visitar nosso Site Gamer</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
        }

        .container {
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        p {
            color: #333;
            line-height: 1.6;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <p>Obrigado por visitar nosso site gamer! Esperamos que você tenha desfrutado da sua experiência aqui, explorando os últimos lançamentos, descobrindo dicas e truques para seus jogos favoritos e mergulhando na cultura vibrante dos games. Estamos sempre atualizando nosso conteúdo para proporcionar a você a melhor experiência de gaming possível. Continue nos acompanhando para ficar por dentro das novidades, análises e eventos emocionantes do mundo dos jogos. Esperamos vê-lo novamente em breve!</p>
    </div>
</body>
</html>

Evolutime/Views/Home/Index.cshtml
@{
    ViewData["Title"]  = "Sobre Games";
}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Explorando o Universo dos Games: Uma Jornada de Emoção e Descoberta</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
        }

        .container {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h2 {
            color: #333;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }

        h3 {
            color: #555;
            margin-top: 30px;
            margin-bottom: 10px;
        }

        p {
            color: #666;
            line-height: 1.6;
            margin-bottom: 20px;
        }

        hr {
            margin-top: 30px;
            margin-bottom: 30px;
            border: none;
            border-top: 2px solid #ccc;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Explorando o Universo dos Games: Uma Jornada de Emoção e Descoberta</h2>
        <hr />

        <p>Os videogames têm trilhado uma jornada extraordinária, evoluindo de simples passatempos a uma indústria global de bilhões de dólares. Hoje, não são apenas uma forma de entretenimento, mas sim um portal para narrativas envolventes, comunidades vibrantes e aprendizado essencial.</p>

        <h3>Diversidade de Experiências:</h3>
        <p>Adentre um vasto universo de possibilidades, onde os videogames abraçam uma miríade de gêneros e estilos. De emocionantes aventuras de RPG que nos transportam a mundos fantásticos a adrenalina pura dos jogos de tiro em primeira pessoa, cada título promete uma experiência única. Estratégia, ação, mistério - há um jogo para cada coração aventureiro.</p>

        <h3>Inovação Tecnológica:</h3>
        <p>Testemunhe o poder da inovação à medida que os limites da realidade são desafiados. Gráficos deslumbrantes em alta definição, realidade virtual que nos transporta para mundos alternativos, inteligência artificial que dá vida a personagens - estas são apenas algumas das façanhas que impulsionam a evolução dos jogos. Prepare-se para mergulhar em experiências que desafiam a própria noção de possibilidade.</p>

        <h3>Conexões Globais:</h3>
        <p>Em um mundo cada vez mais conectado, os videogames servem como ponte entre continentes e culturas. Seja competindo em arenas virtuais ou explorando mundos compartilhados, a comunidade global de jogadores é vasta e acolhedora. Troque estratégias, faça novas amizades e descubra laços que transcendem fronteiras geográficas.</p>

        <h3>Impacto Cultural e Social:</h3>
        <p>Testemunhe o legado duradouro dos videogames na cultura popular. Ícones como 'The Legend of Zelda' e 'Final Fantasy' inspiram gerações, ecoando em obras de arte, música e cinema. Mas o impacto vai além da superfície: os jogos desafiam mentes, promovem a colaboração e ensinam lições valiosas que transcendem o mundo virtual.</p>

        <h3>O Futuro Brilhante:</h3>
        <p>Em um horizonte repleto de possibilidades, o futuro dos videogames reluz com promessas emocionantes. Plataformas emergentes, como a realidade aumentada, ampliam os horizontes da interatividade. Enquanto isso, a inclusão e a acessibilidade crescentes garantem que todos possam participar dessa aventura épica.</p>

        <p>Em resumo, os videogames continuam a nos cativar com sua magia incomparável. Uma fonte eterna de emoção, criatividade e conexão, eles se erguem como pilares da nossa cultura moderna, moldando e inspirando gerações vindouras. Venha, embarque nesta jornada sem igual e descubra o extraordinário mundo dos games.</p>
    </div>
</body>
</html>

Evolutime/Views/Página2/Página2.cshtml
@{
    ViewData["Title"] = "Lista de Jogos: ";
}
<h1>@ViewData["Title"]</h1>

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Jogos Estilizada</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
        }

        .list-group {
            max-width: 600px;
            margin: 20px auto;
        }

        .list-group-item {
            background-color: #fff;
            border: 1px solid #ccc;
            border-radius: 8px;
            margin-bottom: 10px;
        }

            .list-group-item.active {
                background-color: #007bff;
                border-color: #007bff;
                color: #fff;
            }

            .list-group-item:hover {
                background-color: #f8f9fa;
            }

            .list-group-item h5 {
                color: #333;
                margin-bottom: 5px;
            }

            .list-group-item small {
                color: #666;
            }

            .list-group-item p {
                color: #555;
                margin-top: 5px;
            }
    </style>
</head>
<body>
    <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action active" aria-current="true">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">The Witcher 3: Wild Hunt</h5>
                <small>Há 3 dias</small>
            </div>
            <p class="mb-1">The Witcher 3: Wild Hunt é um aclamado jogo de RPG desenvolvido pela CD Projekt Red.</p>
            <small>Aventura, RPG</small>
        </a>
        <a href="#" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Red Dead Redemption 2</h5>
                <small class="text-body-secondary">Há 3 dias</small>
            </div>
            <p class="mb-1">Red Dead Redemption 2 é um jogo de ação-aventura ambientado no Velho Oeste, desenvolvido pela Rockstar Games.</p>
            <small class="text-body-secondary">Ação, Aventura</small>
        </a>
        <a href="#" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">The Legend of Zelda: Breath of the Wild</h5>
                <small class="text-body-secondary">Há 3 dias</small>
            </div>
            <p class="mb-1">The Legend of Zelda: Breath of the Wild é um jogo de aventura da série Zelda desenvolvido pela Nintendo.</p>
            <small class="text-body-secondary">Aventura, RPG</small>
        </a>
    </div>
</body>
</html>

Evolutime/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Games</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Evolutime.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Evolutime</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Página2" asp-action="Página2">Jogos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Agradecimento" asp-action="Agradecimento">Agradecimento</a>
                        </li>
                        
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Evolutime - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>